# Generated by Django 6.0 on 2026-01-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sections',
            field=models.CharField(choices=[('flash', 'flash sale'), ('best', 'best selling'), ('explore', 'Explore')], default='flash', max_length=20),
            preserve_default=False,
        ),
    ]
