# Generated by Django 6.0 on 2026-01-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkoutdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=255)),
                ('lname', models.TextField(max_length=255, null=True)),
                ('street', models.TextField(max_length=255)),
                ('apartment', models.TextField(max_length=255)),
                ('city', models.TextField(max_length=255)),
                ('number', models.IntegerField()),
                ('email', models.IntegerField()),
            ],
        ),
    ]
