# Generated by Django 6.0 on 2026-01-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_checkoutdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='email',
            field=models.TextField(),
        ),
    ]
