# Generated by Django 6.0 on 2026-01-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_alter_checkoutdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
