# Generated by Django 6.0 on 2026-01-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0008_add_to_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_cart',
            name='quantity',
        ),
    ]
